const SOURCE_TYPE_DEFAULTS = {
  rss: {
    provider_key: "generic_rss",
    import_mode: "automatic",
    crawl_method: "rss",
    automation_level: "full_auto",
    parser_type: "rss",
    source_group: "rss",
    trust_level: "needs_review",
  },
  api: {
    provider_key: "custom",
    import_mode: "automatic",
    crawl_method: "api",
    automation_level: "full_auto",
    parser_type: "api",
    source_group: "custom_api",
    trust_level: "needs_review",
  },
  html: {
    provider_key: "custom",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "community",
    trust_level: "needs_review",
  },
  facebook: {
    provider_key: "custom",
    import_mode: "manual",
    crawl_method: "manual",
    automation_level: "manual",
    parser_type: "manual",
    source_group: "community",
    trust_level: "manual_only",
    moderation_required: true,
    notes: "Përdor API zyrtare/leje të qartë ose import manual; mos përdor scraping agresiv.",
  },
  telegram: {
    provider_key: "custom",
    import_mode: "manual",
    crawl_method: "manual",
    automation_level: "manual",
    parser_type: "manual",
    source_group: "community",
    trust_level: "manual_only",
    moderation_required: true,
    notes: "Përdor bot/API kur ka akses të autorizuar; grupet private mbeten manuale.",
  },
  manual: {
    provider_key: "custom",
    import_mode: "manual",
    crawl_method: "manual",
    automation_level: "manual",
    parser_type: "manual",
    source_group: "manual_url",
    trust_level: "manual_only",
    moderation_required: true,
  },
};

function normalizeSourceType(type = "") {
  const value = String(type || "").trim().toLowerCase();
  if (value === "api/json" || value === "json") return "api";
  if (value === "html_needs_review") return "html";
  return SOURCE_TYPE_DEFAULTS[value] ? value : "manual";
}

function technicalDefaultsForSource(source = {}) {
  const sourceType = normalizeSourceType(source.source_type || source.parser_type);
  const defaults = SOURCE_TYPE_DEFAULTS[sourceType] || SOURCE_TYPE_DEFAULTS.manual;
  return {
    ...defaults,
    source_type: sourceType,
  };
}

const INITIAL_IMPORT_SOURCES = [
  {
    seed_key: "arbeitnow-public-api",
    name: "Arbeitnow",
    provider_key: "arbeitnow",
    source_type: "api",
    import_mode: "automatic",
    crawl_method: "api",
    automation_level: "full_auto",
    parser_type: "api",
    source_group: "global_provider",
    trust_level: "medium",
    source_url: "https://www.arbeitnow.com/api/job-board-api",
    base_url: "https://www.arbeitnow.com/api/job-board-api",
    category_filter: "pune",
    country_filter: "Germany",
    parser_config: { max_pages: 25 },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "API publike pa key; njoftimet ruhen si pending_review dhe linkojnë burimin origjinal."
  },
  {
    seed_key: "remoteok-public-api",
    name: "Remote OK",
    provider_key: "custom",
    source_type: "api",
    import_mode: "automatic",
    crawl_method: "api",
    automation_level: "full_auto",
    parser_type: "api",
    source_group: "global_provider",
    trust_level: "medium",
    source_url: "https://remoteok.com/api",
    base_url: "https://remoteok.com/api",
    category_filter: "pune",
    country_filter: "",
    parser_config: { api_format: "remoteok" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Remote OK API publike; kërkon linkim tek burimi origjinal."
  },
  {
    seed_key: "weworkremotely-rss",
    name: "We Work Remotely RSS",
    provider_key: "generic_rss",
    source_type: "rss",
    import_mode: "automatic",
    crawl_method: "rss",
    automation_level: "full_auto",
    parser_type: "rss",
    source_group: "rss",
    trust_level: "medium",
    source_url: "https://weworkremotely.com/remote-jobs.rss",
    base_url: "https://weworkremotely.com/remote-jobs.rss",
    category_filter: "pune",
    country_filter: "",
    parser_config: {},
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "RSS publik; përdoret si fallback kur burimet e tjera sjellin dublikata."
  },
  {
    seed_key: "punajuaj-html",
    name: "PunaJuaj",
    provider_key: "custom",
    source_type: "html",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "albanian_source",
    trust_level: "needs_review",
    source_url: "https://www.punajuaj.com",
    base_url: "https://www.punajuaj.com",
    category_filter: "pune",
    country_filter: "Antokton",
    parser_config: { item_url_patterns: "job,pune,puna,konkurs,vend-pune,vende-pune" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Burim shqiptar publik HTML; njoftimet ruhen për shqyrtim manual."
  },
  {
    seed_key: "portalpune-html",
    name: "PortalPune",
    provider_key: "custom",
    source_type: "html",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "albanian_source",
    trust_level: "needs_review",
    source_url: "https://portalpune.com",
    base_url: "https://portalpune.com",
    category_filter: "pune",
    country_filter: "Antokton",
    parser_config: { item_url_patterns: "job,pune,puna,konkurs,vend-pune,vende-pune" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Burim shqiptar publik HTML; njoftimet ruhen për shqyrtim manual."
  },
  {
    seed_key: "kosovajob-html",
    name: "KosovaJob",
    provider_key: "custom",
    source_type: "html",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "albanian_source",
    trust_level: "needs_review",
    source_url: "https://kosovajob.com",
    base_url: "https://kosovajob.com",
    category_filter: "pune",
    country_filter: "Antokton",
    parser_config: { item_url_patterns: "job,pune,puna,konkurs,vend-pune,vende-pune" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Burim shqiptar publik HTML; njoftimet ruhen për shqyrtim manual."
  },
  {
    seed_key: "merrjep-al-pune-html",
    name: "MerrJep.al Punë",
    provider_key: "custom",
    source_type: "html",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "albanian_source",
    trust_level: "needs_review",
    source_url: "https://www.merrjep.al/njoftime/pune",
    base_url: "https://www.merrjep.al/njoftime/pune",
    category_filter: "pune",
    country_filter: "Antokton",
    parser_config: { item_url_patterns: "njoftime,pune,shpallje,listing" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Burim shqiptar publik HTML; njoftimet ruhen për shqyrtim manual."
  },
  {
    seed_key: "njoftime-pune-html",
    name: "Njoftime.com Punë",
    provider_key: "custom",
    source_type: "html",
    import_mode: "automatic",
    crawl_method: "html",
    automation_level: "full_auto",
    parser_type: "html",
    source_group: "albanian_source",
    trust_level: "needs_review",
    source_url: "https://www.njoftime.com/forum/forums/oferta-pune.25/",
    base_url: "https://www.njoftime.com/forum/forums/oferta-pune.25/",
    category_filter: "pune",
    country_filter: "Antokton",
    parser_config: { item_url_patterns: "threads,oferta-pune,pune,njoftime" },
    enabled: true,
    is_active: true,
    crawl_frequency_minutes: 360,
    notes: "Burim shqiptar publik HTML; njoftimet ruhen për shqyrtim manual."
  }
];

module.exports = {
  INITIAL_IMPORT_SOURCES,
  SOURCE_TYPE_DEFAULTS,
  normalizeSourceType,
  technicalDefaultsForSource,
};
